apiVersion: template.openshift.io/v1
kind: Template
message: Aplicacion Java para Terpel
metadata:
  annotations:
    description: Template para creación de aplicaciones Java para Terpel
    openshift.io/display-name: OpenJDK
  labels:
    template: terpel-fuse7-java-dev
  name: terpel-fuse7-java-dev
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        description: The application's http port.
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentConfig: ${APPLICATION_NAME}
      type: ClusterIP
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      source:
        type: Binary
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: fuse7-java-openshift:1.8
            namespace: openshift
        type: Source
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      triggers: []
      selector:
        deploymentConfig: ${APPLICATION_NAME}
      strategy:
        activeDeadlineSeconds: 7200
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 3600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
            deploymentConfig: ${APPLICATION_NAME}
          name: ${APPLICATION_NAME}
        spec:
          containers:
            - env:
                - name: JVM_OPTIONS
                  value: ${JVM_MSPRVLATAM}
                - name: SPRING_PROFILES_ACTIVE
                  value: openshift
                - name: GOOGLE_CLOUD_PROJECT
                  value: ${GOOGLE_CLOUD_PROJECT}
                - name: STACKDRIVER_LOG_NAME
                  value: ${APPLICATION_NAME}-${ENVIRONMENT}
                - name: TZ
                  value: America/Bogota
                - name: PROJECT_ID
                  value: ${GCP_PROJECT_ID}
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /deployments/credentials/sa-gcp.json
                - name: CLIENTID
                  valueFrom:
                    secretKeyRef:
                      name: secret-${APPLICATION_NAME}-credentials
                      key: CLIENTID
                - name: CLIENTSECRET
                  valueFrom:
                    secretKeyRef:
                      name: secret-${APPLICATION_NAME}-credentials
                      key: CLIENTSECRET
                - name: PRODUCTCODEACC
                  valueFrom:
                    secretKeyRef:
                      name: secret-${APPLICATION_NAME}-credentials
                      key: PRODUCTCODEACC
                - name: TOKEN_REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: secret-${APPLICATION_NAME}-credentials
                      key: TOKEN_REDIS_PASSWORD
                - name: BASEPATH
                  valueFrom:
                    configMapKeyRef:
                      name: configurations-${APPLICATION_NAME}
                      key: ms.configuration.service.webclient.latam.basepath
                - name: PATHSERVICETOKEN
                  valueFrom:
                    configMapKeyRef:
                      name: configurations-${APPLICATION_NAME}
                      key: ms.configuration.service.webclient.latam.pathservicetoken
                - name: PATHSERVICEGETMEMBERINFO
                  valueFrom:
                    configMapKeyRef:
                      name: configurations-${APPLICATION_NAME}
                      key: ms.configuration.service.webclient.latam.pathServiceGetMemberInfo
                - name: PATHACCRUAL
                  valueFrom:
                    configMapKeyRef:
                      name: configurations-${APPLICATION_NAME}
                      key: ms.configuration.service.webclient.latam.path_accrual
                - name: PATHTRANSFERPOINT
                  valueFrom:
                    configMapKeyRef:
                      name: configurations-${APPLICATION_NAME}
                      key: ms.configuration.service.webclient.latam.pathServiceTransferPoint
                - name: PATHTRANSFERPOINTLATAM
                  valueFrom:
                    configMapKeyRef:
                      name: configurations-${APPLICATION_NAME}
                      key: ms.configuration.service.webclient.latam.pathServiceTransferPointLatam
                - name: BASEPATHSALESFORCE
                  valueFrom:
                    configMapKeyRef:
                      name: configurations-${APPLICATION_NAME}
                      key: ms.configuration.service.webclient.latam.basePathSalesforce
                - name: GRANTTYPE
                  valueFrom:
                    configMapKeyRef:
                      name: configurations-${APPLICATION_NAME}
                      key: ms.configuration.service.webclient.latam.grant_type
                - name: SCOPE_MEMBER_SHOW
                  valueFrom:
                    configMapKeyRef:
                      name: configurations-${APPLICATION_NAME}
                      key: ms.configuration.service.webclient.latam.scope_member_show
                - name: SCOPE_ACCRUAL_CREATE
                  valueFrom:
                    configMapKeyRef:
                      name: configurations-${APPLICATION_NAME}
                      key: ms.configuration.service.webclient.latam.scope_accrual_create
                - name: PRODUCTNAME
                  valueFrom:
                    configMapKeyRef:
                      name: configurations-${APPLICATION_NAME}
                      key: ms.configuration.service.webclient.latam.product_name_accrual
                - name: TOKEN_REDIS_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: configurations-${APPLICATION_NAME}
                      key: configuration.redis.connection.host
                - name: TOKEN_REDIS_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: configurations-${APPLICATION_NAME}
                      key: configuration.redis.connection.port
                - name: TOKEN_REDIS_KEY
                  valueFrom:
                    configMapKeyRef:
                      name: configurations-${APPLICATION_NAME}
                      key: configuration.redis.connection.keyRedis
              image: ${APPLICATION_NAME}
              imagePullPolicy: Always
              name: ${APPLICATION_NAME}
              ports:
                - containerPort: 8080
                  protocol: TCP
              livenessProbe:
                failureThreshold: 8
                httpGet:
                  path: /actuator/health
                  port: ${{ACTUATOR_PORT}}
                  scheme: HTTP
                initialDelaySeconds: 100
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 1
              readinessProbe:
                failureThreshold: 8
                httpGet:
                  path: /actuator/health
                  port: ${{ACTUATOR_PORT}}
                  scheme: HTTP
                initialDelaySeconds: 40
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  cpu: 300m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
              volumeMounts:
                - mountPath: /deployments/credentials
                  name: secret-gcp
                  readOnly: true
          volumes:
            - secret:
                defaultMode: 420
                secretName: secret-gcp
              name: secret-gcp
      latestVersion: 5
      observedGeneration: 10
      readyReplicas: 1
      unavailableReplicas: 0
      updatedReplicas: 1
parameters:
  - description: The name for the application.
    displayName: Nombre de la aplicación
    name: APPLICATION_NAME
    required: true
    value: openjdk-app
  - description: Ambiente donde está desplegada la aplicación (dev / qa / prd)
    displayName: Ambiente donde está desplegada la aplicación (dev / qa / prd)
    name: ENVIRONMENT
    required: true
    value: dev
  - description: The name of project gcp
    displayName: Proyecto GCP
    name: GCP_PROJECT_ID
    required: true
    value: terpel-infra-sharedvpc-oshift
  - description: Mínimo numero de réplicas
    displayName: Mínimo numero de réplicas
    name: MIN_REPLICAS
    required: true
    value: '1'
  - description: Porcentaje de utilización de CPU para Autoscaling
    displayName: Porcentaje de utilización de CPU para Autoscaling
    name: TARGET_CPU_UTILIZATION_PERCENTAJE
    required: true
    value: '70'
  - description: Nombre proyecto GOOGLE_CLOUD_PROJECT
    displayName: Nombre proyecto GOOGLE_CLOUD_PROJECT
    name: GOOGLE_CLOUD_PROJECT
    required: true
    value: 'terpel-infra-sharedvpc-oshift'
  - description: Puerto del actuador de spring usado para los health checks
    displayName: Puerto del actuador de spring usado para los health checks
    name: ACTUATOR_PORT
    required: true
    value: '8080'
  - description: Opciones JVM
    displayName: Opciones JVM
    name: JVM_MSPRVLATAM
    required: true
    value: '-Xmx538m -Xms270m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=256m -XX:+UseParallelGC -XX:ParallelGCThreads=2 -XX:GCTimeRatio=16 -XX:ConcGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -XX:CICompilerCount=2 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError'
